### ISSUE TITLE
Is it possible to add documents

### ISSUE THREAD

**Issue by ghost** [StackStorm-Exchange/stackstorm-elasticsearch#15]
Is it possible to add documents to an indice with this package? If not, is there another pack that has this option? I have not found

**Comment by blag** [comment]
No, this pack does not have an explicit action that help you add documents to an Elasticsearch index.

However, adding documents to Elasticsearch seems to be [pretty easy](https://marcobonzanini.com/2015/02/02/how-to-query-elasticsearch-with-python/):

> ```bash
> curl -XPOST https://localhost:9200/test/articles/1 -d '{"content": "The quick brown fox"}'
> ```
> 
> This commands creates a new document, and since the index didn’t exist, it also creates the index. Specifically, the format for the URL is:
> 
> ```
> https://hostname:port/index_name/doc_type/doc_id
> ```

So you can just use StackStorm's [built-in `core.http` action](https://docs.stackstorm.com/actions.html#pre-defined-actions) to send an HTTP request to your ES server with the document you want to create:

```bash
st2 run core.http method="POST" url="https://localhost:9200/test/articles/1" body='{"content": "The quick brown fox"}'
```

Or, in an Orquesta workflow:

```yaml
tasks:
  ...
  action: core.http
  input:
    method: POST
    url: https://localhost:9200/test/articles/1
    body: '{"content": "The quick brown fox"}'
  ...
```

I suspect the reason that nobody has added an action to this pack that explicitly adds a document to an index is because it is so very easy to do it with a simple HTTP request via `core.http`. However, if you think an explicit action would be useful for you, then we would be happy to accept pull requests that implement that functionality.

The action metadata for `core.http` can be found [here](https://github.com/StackStorm/st2/blob/master/contrib/core/actions/http.yaml) and the metadata for the `http-request` action runner (including the additional runner parameters) can be found [here](https://github.com/StackStorm/st2/blob/master/contrib/runners/http_runner/http_runner/runner.yaml).
